In [ ]:
#%%

import os
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from matplotlib import colors
from matplotlib import rcParams
import seaborn as sns
from gprofiler import GProfiler
import sys
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#%%

import configparser

# Read configuration file
config = configparser.ConfigParser()
config.read("../../utils/config.ini")

rawPath = config.get("DEFAULT", "rawPath")
scriptsPath = config.get("DEFAULT", "scriptsPath")
figPath = config.get("DEFAULT", "figPath")
gprofFolder = scriptsPath + "9_testing/GProfiler/"

integrationDir = rawPath + 'integration/metacells/cancer/'

path = "/group/testa/Project/OvarianAtlas/atlas_project/raw_data/out_of_sample_extension_backup/out_of_sample_extension/fibroblasts/integrated_query_zheng_seacells_scarches_tissuetreat_predicted_cellstates.h5ad"
adata = sc.read_h5ad(path)

In [ ]:
adata.raw

In [ ]:
path_ad =  rawPath + "integration/metacells/fibroblasts_testing/seacells_hdg_patients_batch_corr_scgen_scarches_tissuetreat.h5ad"

In [ ]:
path_ad

'/group/testa/Project/OvarianAtlasTestStep0/raw_data/integration/metacells/fibroblasts_testing/seacells_hdg_patients_batch_corr_scgen_scarches_tissuetreat.h5ad'

In [ ]:
ad = sc.read_h5ad(path_ad)

In [ ]:
ad

AnnData object with n_obs × n_vars = 6639 × 5179
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells', 'tissue-treatment'
    obsm: 'latent_corrected'
    layers: 'original_data'

In [ ]:
ad.raw

In [ ]:
ad = sc.read_h5ad("/group/testa/Project/OvarianAtlas/atlas_project/raw_data/metacells_backup/metacells/fibroblasts/" + "seacells_hdg_patients.h5ad")

In [ ]:
ad

AnnData object with n_obs × n_vars = 6639 × 17063
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells'
    layers: 'raw'

In [ ]:
ad.obs_names

Index(['SEACell-137_Geistlinger_59_Metastasis',
       'SEACell-76_Geistlinger_59_Metastasis',
       'SEACell-108_Geistlinger_59_Metastasis',
       'SEACell-135_Geistlinger_59_Metastasis',
       'SEACell-101_Geistlinger_59_Metastasis',
       'SEACell-126_Geistlinger_59_Metastasis',
       'SEACell-105_Geistlinger_59_Metastasis',
       'SEACell-84_Geistlinger_59_Metastasis',
       'SEACell-75_Geistlinger_59_Metastasis',
       'SEACell-92_Geistlinger_59_Metastasis',
       ...
       'SEACell-15_Vasquez_118_Metastasis',
       'SEACell-31_Vasquez_118_Metastasis',
       'SEACell-35_Vasquez_118_Metastasis',
       'SEACell-41_Vasquez_118_Metastasis',
       'SEACell-14_Vasquez_118_Metastasis', 'SEACell-9_Vasquez_118_Metastasis',
       'SEACell-49_Vasquez_118_Metastasis',
       'SEACell-21_Vasquez_118_Metastasis',
       'SEACell-28_Vasquez_118_Metastasis',
       'SEACell-46_Vasquez_118_Metastasis'],
      dtype='object', name='SEACell_patient_tissue', length=6639)

In [ ]:
adata

AnnData object with n_obs × n_vars = 7276 × 5179
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells', 'tissue-treatment', 'reference_map', 'original_batch', 'concat_batch', 'primary_state', 'ascites_state', 'metastasis_state', 'cell_states'
    uns: 'cell_states_colors', 'dataset_colors', 'neighbors', 'paper_ID_colors', 'pca', 'tissue-treatment_colors', 'tissue_colors', 'treatment_colors', 'umap'
    obsm: 'X_pca', 'X_umap', 'latent_corrected'
    varm: 'PCs'
    layers: 'original_data'
    obsp: 'connectivities', 'distances'

In [ ]:
adata.obs_names

Index(['SEACell-137_Geistlinger_59_Metastasis',
       'SEACell-76_Geistlinger_59_Metastasis',
       'SEACell-108_Geistlinger_59_Metastasis',
       'SEACell-135_Geistlinger_59_Metastasis',
       'SEACell-101_Geistlinger_59_Metastasis',
       'SEACell-126_Geistlinger_59_Metastasis',
       'SEACell-105_Geistlinger_59_Metastasis',
       'SEACell-84_Geistlinger_59_Metastasis',
       'SEACell-75_Geistlinger_59_Metastasis',
       'SEACell-92_Geistlinger_59_Metastasis',
       ...
       'SEACell-6_Zheng_10_Ascites', 'SEACell-18_Zheng_10_Ascites',
       'SEACell-0_Zheng_10_Primary', 'SEACell-9_Zheng_10_Primary',
       'SEACell-8_Zheng_10_Primary', 'SEACell-1_Zheng_10_Primary',
       'SEACell-3_Zheng_10_Primary', 'SEACell-10_Zheng_10_Primary',
       'SEACell-18_Zheng_10_Primary', 'SEACell-6_Zheng_10_Primary'],
      dtype='object', name='SEACell_patient_tissue', length=7276)

In [ ]:
ad.raw.X

AttributeError: 'NoneType' object has no attribute 'X'

In [ ]:
ad_raw = ad.raw.to_adata()

AttributeError: 'NoneType' object has no attribute 'to_adata'

In [ ]:
ad

AnnData object with n_obs × n_vars = 6639 × 17063
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells'
    layers: 'raw'

In [ ]:
ad.X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 55854324 stored elements and shape (6639, 17063)>

In [ ]:
ad.X.todense()

matrix([[  0.        ,   2.81594658,   0.        , ..., 156.12287903,
          31.13029861, 223.87612915],
        [  0.        ,   0.        ,   0.        , ..., 351.97628784,
          70.73066711, 626.02392578],
        [  0.        ,   2.20868397,   2.21374941, ..., 399.04098511,
          95.96352386, 675.01550293],
        ...,
        [  0.        ,   1.13627982,   0.        , ...,  23.87796402,
           7.92604923,  38.23749161],
        [  0.        ,   0.        ,   0.        , ...,  73.29381561,
          24.51880455, 123.72459412],
        [  0.        ,   0.        ,   1.14566827, ...,  40.74865723,
          13.07326221,  86.73073578]])

In [ ]:
ad = sc.read_h5ad(initDir + "seacells_hdg_patients.h5ad")

NameError: name 'initDir' is not defined

In [ ]:
integrationDir = rawPath + 'integration/metacells/fibroblasts/'

In [ ]:
ad = sc.read_h5ad(integrationDir + "seacells_hdg_patients.h5ad")

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/group/testa/Project/OvarianAtlasTestStep0/raw_data/integration/metacells/fibroblasts/seacells_hdg_patients.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
integrationDir = rawPath + 'integration/metacells/fibroblast/'

In [ ]:
ad = sc.read_h5ad(integrationDir + "seacells_hdg_patients.h5ad")

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/group/testa/Project/OvarianAtlasTestStep0/raw_data/integration/metacells/fibroblast/seacells_hdg_patients.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
integrationDir = rawPath + 'integration/metacells/fibroblasts/'

In [ ]:
ad = sc.read_h5ad(integrationDir + "seacells_hdg_patients.h5ad")

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/group/testa/Project/OvarianAtlasTestStep0/raw_data/integration/metacells/fibroblasts/seacells_hdg_patients.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
ad = sc.read_h5ad(initDir + "seacells_hdg_patients_batch_corr_scgen_celltypes_HDG.h5ad")

NameError: name 'initDir' is not defined

In [ ]:
ad = sc.read_h5ad(integrationDir + "seacells_hdg_patients_batch_corr_scgen_celltypes_HDG.h5ad")

In [ ]:
ad

AnnData object with n_obs × n_vars = 6654 × 5179
    obs: 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'dataset', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'max', 'cell_types', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', '_scvi_batch', '_scvi_labels'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
ad.raw

In [ ]:
ad.raw.to_adata()

AnnData object with n_obs × n_vars = 6654 × 17063
    obs: 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'dataset', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'max', 'cell_types', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', '_scvi_batch', '_scvi_labels'
    var: 'highly_variable'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
path = "/group/testa/Project/OvarianAtlas/atlas_project/raw_data/out_of_sample_extension_backup/out_of_sample_extension/fibroblasts/integrated_query_zheng_seacells_scarches_tissuetreat_predicted_cellstates.h5ad"
adata = sc.read_h5ad(path)


In [ ]:
adata

AnnData object with n_obs × n_vars = 7276 × 5179
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells', 'tissue-treatment', 'reference_map', 'original_batch', 'concat_batch', 'primary_state', 'ascites_state', 'metastasis_state', 'cell_states'
    uns: 'cell_states_colors', 'dataset_colors', 'neighbors', 'paper_ID_colors', 'pca', 'tissue-treatment_colors', 'tissue_colors', 'treatment_colors', 'umap'
    obsm: 'X_pca', 'X_umap', 'latent_corrected'
    varm: 'PCs'
    layers: 'original_data'
    obsp: 'connectivities', 'distances'

In [ ]:
ad.raw.to_adata()

AnnData object with n_obs × n_vars = 6654 × 17063
    obs: 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'dataset', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'max', 'cell_types', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', '_scvi_batch', '_scvi_labels'
    var: 'highly_variable'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
integrationDir 

'/group/testa/Project/OvarianAtlasTestStep0/raw_data/integration/metacells/fibroblasts/'

In [ ]:
integrationDir = "/group/testa/Project/OvarianAtlas/atlas_project/raw_data/integration_backup/integration/metacells/fibroblasts"

In [ ]:
integrationDir

'/group/testa/Project/OvarianAtlas/atlas_project/raw_data/integration_backup/integration/metacells/fibroblasts'

In [ ]:
ad = sc.read_h5ad(integrationDir + "seacells_hdg_patients_batch_corr_scgen_celltypes_HDG.h5ad")

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/group/testa/Project/OvarianAtlas/atlas_project/raw_data/integration_backup/integration/metacells/fibroblastsseacells_hdg_patients_batch_corr_scgen_celltypes_HDG.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
ad = sc.read_h5ad(integrationDir + "/seacells_hdg_patients_batch_corr_scgen_celltypes_HDG.h5ad")

In [ ]:
ad

AnnData object with n_obs × n_vars = 6639 × 5179
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', 'cell_types', '_scvi_batch', '_scvi_labels'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
ad.raw

In [ ]:
adata_target_path = "/group/testa/Project/OvarianAtlasTestStep0/raw_data/metacells_step0/fibroblasts/" + 'seacells_hdg_patients.h5ad'


In [ ]:
adata_target_path

'/group/testa/Project/OvarianAtlasTestStep0/raw_data/metacells_step0/fibroblasts/seacells_hdg_patients.h5ad'

In [ ]:
adata_target = sc.read_h5ad(adata_target_path)

In [ ]:
adata_target

AnnData object with n_obs × n_vars = 6654 × 17063
    obs: 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'dataset', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'max', 'cell_types', 'SEACell', '# Single Cells'
    layers: 'raw'

In [ ]:
adata_target.X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 55966000 stored elements and shape (6654, 17063)>

In [ ]:
adata_target.X.todense()

matrix([[  0.        ,   0.        ,   0.        , ...,  48.7358636 ,
          12.5818196 ,  62.26993987],
        [  0.        ,   1.09280197,   0.        , ..., 125.25545644,
          30.19462604, 191.35574785],
        [  1.18174646,   3.10814885,   0.        , ..., 192.71310593,
          45.61751611, 269.4842292 ],
        ...,
        [  0.        ,   0.        ,   0.        , ...,  42.46663578,
          18.84778225,  57.38638132],
        [  0.        ,   0.        ,   0.76345106, ...,  20.6494489 ,
           8.55138469,  33.46049622],
        [  0.        ,   0.        ,   0.        , ...,  25.55855056,
           6.35548407,  30.63254473]])

In [ ]:
ad

AnnData object with n_obs × n_vars = 6639 × 5179
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', 'cell_types', '_scvi_batch', '_scvi_labels'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
integrationDir

'/group/testa/Project/OvarianAtlas/atlas_project/raw_data/integration_backup/integration/metacells/fibroblasts'

In [ ]:
ad.rae

AttributeError: 'AnnData' object has no attribute 'rae'

In [ ]:
ad.raw()

TypeError: 'Raw' object is not callable

In [ ]:
ad.raw.to_adata()

AnnData object with n_obs × n_vars = 6639 × 17063
    obs: 'ID', 'sample_name', 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'patient_id', 'dataset', 'cell_type', 'cell_subtype', 'sample_ID', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'cell_labels_ratio', 'max', 'assignment', 'leiden-1.8', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', 'cell_types', '_scvi_batch', '_scvi_labels'
    var: 'highly_variable'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
adata_step = sc.read_h5ad("/group/testa/Project/OvarianAtlasTestStep0/raw_data/integration/metacells/fibroblasts/seacells_hdg_patients_batch_corr_scgen_celltypes_HDG.h5ad")

In [ ]:
adata_step

AnnData object with n_obs × n_vars = 6654 × 5179
    obs: 'tissue', 'developmental_stage', 'treatment', 'recurrence', 'tumor_stage', 'paper_ID', 'anatomical_location', 'dataset', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'CancerMSK', 'EndothelialMSK', 'FibroblastsMSK', 'HematopoieticMSK', 'max', 'cell_types', 'SEACell', '# Single Cells', 'tissue-treatment', 'iCAF', 'mCAF', 'vCAF', 'starCAF', '_scvi_batch', '_scvi_labels'
    uns: '_scvi_manager_uuid', '_scvi_uuid'
    obsm: 'corrected_latent', 'latent'

In [ ]:
adata_step.raw.to_adata().X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 55966000 stored elements and shape (6654, 17063)>

In [ ]:
adata_step.raw.to_adata().X.todense()

matrix([[0.        , 0.        , 0.        , ..., 3.90672627, 2.6087321 ,
         4.14741033],
        [0.        , 0.73850382, 0.        , ..., 4.83830729, 3.44024584,
         5.25934651],
        [0.78012568, 1.41297252, 0.        , ..., 5.26637823, 3.84197635,
         5.60021379],
        ...,
        [0.        , 0.        , 0.        , ..., 3.77199365, 2.98809228,
         4.06708267],
        [0.        , 0.        , 0.56727272, ..., 3.07498   , 2.25668614,
         3.53981363],
        [0.        , 0.        , 0.        , ..., 3.27935175, 1.99544617,
         3.45418649]])

In [ ]:
ad.raw.to_adata().X.todense()

matrix([[0.        , 1.3391887 , 0.        , ..., 5.0570283 , 3.4697995 ,
         5.4155498 ],
        [0.        , 0.        , 0.        , ..., 5.8664007 , 4.272918  ,
         6.4409847 ],
        [0.        , 1.1658609 , 1.1674383 , ..., 5.991567  , 4.574335  ,
         6.516216  ],
        ...,
        [0.        , 0.7590659 , 0.        , ..., 3.2139823 , 2.188974  ,
         3.6696327 ],
        [0.        , 0.        , 0.        , ..., 4.3080277 , 3.2394156 ,
         4.826108  ],
        [0.        , 0.        , 0.76345104, ..., 3.7316673 , 2.6442766 ,
         4.4742723 ]], dtype=float32)